### ISSUE TITLE
BackOffice_2 posters site wont build after fresh maven build

### ISSUE THREAD

**Issue by EliasTatX** [Xceptance/posters-demo-store#109]
After a fresh maven build with mvn clean and mvn process-classes attempting to start the posters site in the console throws errors and crashes unsuccessfully. The site will not be accessible in Chrome and neither is the backoffice. Without a fresh build the site will load but the backoffice will be unavailable (as is to be expected).
![Screenshot from 2023-07-07 11-14-25](https://github.com/Xceptance/posters-demo-store/assets/112633288/b920e1b5-ae42-4b1b-9576-dec6822e5a58)
Please verify the stability of the current version and/or tag the latest stable version to allow testing.

**Comment by Kenspectacle** [comment]
Resolved, updated the pom and the conf files to include the backoffice models
