### ISSUE TITLE
Task Update - Cloning Posters and Setting Up Demo Store

### ISSUE THREAD

**Issue by msaroshali** [Xceptance/posters-demo-store#11]
Tasks
- [x] Cloning Posters
- [x] Obtaining the design template
- [x] Creating a separate branch for this work
- [x] Setting up the Posters Demo Store to run locally.

**Comment by rschwietzke** [comment]
Hint: You describe what to do (not as personal message) and as part o the comments, you say what is done.  Don't see that as a letter to readers:)

You can also use task lists: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#task-lists

- [ ] Task 1
- [ ] Task 2

**Comment by msaroshali** [comment]
Thanks. Have modified the description.
