### ISSUE TITLE
Backoffice: Sections Requirements

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/posters-demo-store#116]
# Goal

We want to have logical sections with subtopics.

# Sections (to show and open)

* Dashboard: Just a board that will show stats and other nifty things soon
* Catalog (the catalog administration): Search, Categories, Products
* Customers (store customers):  Search, List
* Orders (all incoming orders): Search, List
* Users (administrators): Search, List
* Preferences: List

## Search 

Each section features a search screen with the ability to search for items within that context (such as user, customers, and so on). This section differs from the quick search. It is more an advanced search (prio low). For the moment, just place a placeholder here.

## Preferences

Place a placeholder here until we have defined more of the content.

# Basic Elements

The UI features a left navigation section (1), a header with a quick search for customers, products, and orders (2) as well as a user avatar and menu (3). A footer with copyright and source links will be at the bottom (4).  The middle section is the main content areas. (5).

![Image](https://github.com/Xceptance/posters-demo-store/assets/1793856/dc6a12c4-48c4-49b5-856f-9d255a82d64b)

**Comment by EliasTatX** [comment]
Current state after my first round of work:
![Screenshot from 2023-08-23 12-26-55](https://github.com/Xceptance/posters-demo-store/assets/112633288/295f4cf6-009d-43d8-bb2e-880d2fb44314)
![Screenshot from 2023-08-23 12-27-13](https://github.com/Xceptance/posters-demo-store/assets/112633288/d923f2bc-53a1-49f4-ade8-d8f0a7d80ef5)
![Screenshot from 2023-08-23 12-27-23](https://github.com/Xceptance/posters-demo-store/assets/112633288/4853c958-d4c1-49e2-8376-a1e0f4b8ae48)
![Screenshot from 2023-08-23 12-27-32](https://github.com/Xceptance/posters-demo-store/assets/112633288/863c5dfe-7818-4abb-80f0-f96f7ba4daa6)
![Screenshot from 2023-08-23 12-27-40](https://github.com/Xceptance/posters-demo-store/assets/112633288/5f3ce7e7-f42a-4610-ba6d-4577680669b5)
![Screenshot from 2023-08-23 12-27-52](https://github.com/Xceptance/posters-demo-store/assets/112633288/b11162a8-63cd-4fbc-84d6-ada16fe860ba)
Does this match the desired sections that were meant to be introduced? Is there anything that should be improved?

**Comment by rschwietzke** [comment]
We might likely want to restyle the submenus on the left but the Dashmin delivers it that one, so we take that for the moment and invest later more into this area. Good so far.
