### ISSUE TITLE
Backoffice: Customer Requirements

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/posters-demo-store#118]
# Goal
Deliver a simple way of managing customers including but not limited to searching, editing, removing.

# Section
Use the customer section for this feature, it will have to subsections.

## Search
A search screen that allows to search for ID, name, last name, and email. At the moment, this is an AND-search (for all fields filled in) and will produce a list (table) underneath the search screen as result. The list is pageable. 

## List
Another screen directly offers a list of all customers without the need to search for. It will deliver a list of customers (pageable) by last name, first name. 

# Lists
All table lists will list id, last name, first name, email, status, and offer a VIEW, EDIT. DELETE buttons.

# VIEW
The view button takes us to a listing which is nicely formatted and displays all important information attached to the customer, such as basic data, addresses, and more.  An additional button allows to jump to all orders of the customer (which is basically a search by customer id using the order search module and we really jump to it).

# DELETE
You can delete a customer after confirmation BUT it won't delete the customer's orders(!). Important, make sure that the data such as addresses and credit cards is copied to the order when placing the order and not referenced!

# EDIT
Here you can edit all customer information including assigning a new password (that is not really security conform but this a demo store and we don't have email support yet).

## Addresses
Addresses will be listed on the EDIT screen and you have to use a separate edit step. You an also delete an address.

## Credit Cards
CC can be removed or edited but you can only enter the number, name, and expiration date, not the CVV. This will be asked in the storefront again when ordering and will never ever be stored.

# Removing
You can remove an address or a credit card but you have to of course confirm that.

# Navigation
For most of the screen, a back navigation in the browser should work nicely and produce the screen expected. Especially important for searches and paging.

**Comment by msaroshali** [comment]
![image](https://github.com/Xceptance/posters-demo-store/assets/22943352/1233f015-85e0-4942-abad-66490942818b)
Currently after the table updates the List View looks like this. Interestingly we have same views for Customer Search View and List View atm. Would require separate controller methods for that. 
**Question**: Is it possible we just have one List view for Customers with the ability to search through it? Instead of having a simple List view and a search-able List View.

**Comment by rschwietzke** [comment]
> Is it possible we just have one List view for Customers with the ability to search through it? Instead of having a simple List view and a search-able List View.
The implementation details are up to you. Choose the best path. One only one list view is likely a wise decision.

**Comment by msaroshali** [comment]
Cannot, as of yet, delete a customer without affecting customer's Orders. Currently the database and its tables do not permit this flexibility. It requires an independent issue #245 . Closing this issue as remaining objectives have been achieved.
