### ISSUE TITLE
Icon flyouts: should not stay open on click; open corresponding pages instead 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#124]
Enviroment: Chrome, Edge (Win 10) 

Reproduce: 
1. Mouse over account/cart icon 
2. When the corresponing flyout opens, click on account/cart icon 

Issue: note the flyout turns fuzzy. Only reproducible when doing this the first time. Also not reproducible in FF, specific to Chrome and Edge. We might consider removing this feature altogether. 

Screencast: https://github.com/Xceptance/posters-demo-store/assets/141221329/f3dd835e-2804-4fd7-bca2-38ebd666c141

![2023-08-04_10h36_46](https://github.com/Xceptance/posters-demo-store/assets/141221329/3a0fa8d0-45f2-4000-b06a-17c2fde90076)

**Comment by kqmpetenz** [comment]
I suggest to only be able to open the mini cart via hover (same for user menu). Also when you open the mini cart, the window just plops up instantly. I think it would be better if we have some kind of animnation, just like the categories of the top navigation.

**Comment by rschwietzke** [comment]
PO: Only one drop-down must be active at any time. It is recommended to remove the "on click" action and keep the hover action only. This should automatically give us what we want.

**Comment by KFie** [comment]
Adjusting ticket summary to emphasize that click-action needs to be removed. Instead, we need the icons to be clickable and open target pages to increase mobile usability. 

Click on cart icon: opens cart page
Click on account icon: opens page showing log in form and registration form (which is currently not existing)

**Comment by freddyka** [comment]
The issue is resolved for poster v2.1.
