### ISSUE TITLE
Account icon in logged in state: tooltip wrog 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#125]
Reproduce: 
1. Log in 
2. Mouse over account icon to trigger tooltip 

Issue:  Tooltip reads "Sign in" (which it does in not logged in state). This doesn't apply here as the user is logged in already. 

![image](https://github.com/Xceptance/posters-demo-store/assets/141221329/cabafc13-34c4-41fe-a0c9-b212a38beb39)

**Comment by freddyka** [comment]
Issue remains for poster v2.1.
