### ISSUE TITLE
Empty cart flyout: should not display subtotal and "View Cart" button 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#126]
Reproduce: 
1. Make sure to have no items in cart 
2. Mouse over cart icon to trigger flyout 

Issue: The empty cart flyout doesn't differ much from the flyout of a cart with items as it displays a subtotal of 0 and a "View cart" button. This is not very common, the "View Cart" button doesn't make sense. I recommend to adjust the content of the overlay for empty carts, possibly by using a message saying "You have no items in your cart". 

![2023-08-04_10h44_34](https://github.com/Xceptance/posters-demo-store/assets/141221329/c496ed6a-4b69-422a-bc86-3b19f8b406f5)

**Comment by rschwietzke** [comment]
An empty cart should not have fly-out. It already displays all the information. There is also no need to go to the cart.

**Comment by freddyka** [comment]
Issue not fixed for poster v2.1.

**Comment by msaroshali** [comment]
Continuing this issue with issue #313
