### ISSUE TITLE
PDP: add to cart button label should be white 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#131]
Reproduce: 
1. Open random PDP such as https://34.70.184.112:8443/posters/productDetail/Grizzly%20Bear?productId=1

Issue: The "Add to cart" button deviates from the other red CTAs across the site (compare with CTAs in checkout) as follows: 
1. The "Add to cart" text is black by default. Expected: White. 
2. The button's hover state is very specific. On hover, the button shows a movement (it shrinks) and the label changes its color. This is not consistent with the other buttons of that category. Expected: On hover, the button color should turn darker, no change in button size, no change in font color. 

![2023-08-04_12h37_28](https://github.com/Xceptance/posters-demo-store/assets/141221329/bac3b221-503d-4974-97cf-7775f46aae7c)

**Comment by rschwietzke** [comment]
Unify the button styling, don't use any local styling and reuse the common style. See the #44

**Comment by EliasTatX** [comment]
Resolved during the work on #192 Fonts, Font Sizes, Buttons

**Comment by freddyka** [comment]
Issue is resolved for poster v2.1.
