### ISSUE TITLE
PDP: select style radio buttons need layout and spelling adjustment 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#132]
Reproduce: 
1. Open random PDP such as https://34.70.184.112:8443/posters/productDetail/Great%20Grey%20Owl?productId=2

Issue: The display of the style radio button section should be improved as follows: 
1. Increase the padding between the size dropdown and the style selection
2. Improve alignment of "matte" and "gloss" values with radio buttons: there is not enough padding and the terms are not horizontally centered to the radio buttons 
3. Change spelling of "matte" and "gloss" to "Matte" and "Gloss"

![image](https://github.com/Xceptance/posters-demo-store/assets/141221329/3d982fbe-0852-4c4f-9b80-7c5995917675)

**Comment by freddyka** [comment]
Issue is completed for poster v2.1.
