### ISSUE TITLE
PDP: layout improvement suggestions

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#133]
Reproduce: 
1. open random PDP such as https://34.70.184.112:8443/posters/productDetail/Great%20Grey%20Owl?productId=2

Issue: the PDPs layout could be improved in several ways to increase readability.

1. There is a lot of padding between the header banner and the first content elements. Is it really needed? 
2. The product description overview is too large compared to the product name and price value 
3. The main image is too small, there is lots of white space between the image and the content on the right hand side 
4. The overall font size of the individual elements is very small, especially product description, size, style and print information section and add to cart button label. 
 
![2023-08-04_12h50_42](https://github.com/Xceptance/posters-demo-store/assets/141221329/26f27b13-e865-40e3-b771-673e422c0822)

Possible improvement could look like this maybe? 
![2023-08-04_09h27_29](https://github.com/Xceptance/posters-demo-store/assets/141221329/d0110aae-ba7b-4ae0-a7f8-77b9662dab84)

("Add to cart" button label size will be addressed elsewhere as this is a global issue.)

**Comment by freddyka** [comment]
Issue is fixed for poster version 2.1.
