### ISSUE TITLE
Cart: hide progress indicator 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#134]
Reproduce: 
1. add random item to cart 
2. open cart 

Issue: The progress indicator should not show here. It is not common since the cart is not part of the actual checkout process. Plus, the customer learns at this point they will have to go through 6 steps to submit their order. Not very motivating. 

![2023-08-04_12h57_00](https://github.com/Xceptance/posters-demo-store/assets/141221329/b1cd6877-febd-4db6-bcdd-de9caa5c08a0)

Also see https://github.com/Xceptance/posters-demo-store/issues/168 and https://github.com/Xceptance/posters-demo-store/issues/169.

**Comment by freddyka** [comment]
Is fixed for poster v2.1.
