### ISSUE TITLE
Empty cart page: change text styling 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#135]
Reproduce: 
1. open empty cart page 

Issue: Note the "Your cart is empty. Continue shopping." text is almost styled like the global error messages (compare with failed login error, for instance). I suggest to style this differently, at least leave out the red color as it looks too much like an error scenario. 

Empty cart message: 
![2023-08-04_13h02_20](https://github.com/Xceptance/posters-demo-store/assets/141221329/188df91f-bea7-4f83-96cd-05769aefc7fa)

... almost looks like error: 
![2023-08-04_13h05_45](https://github.com/Xceptance/posters-demo-store/assets/141221329/68026c64-a86f-4f14-bd2f-696d7a0dc373)

**Comment by freddyka** [comment]
Issue remains for poster v2.1.
