### ISSUE TITLE
Account: poor navigation 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#137]
1. Log in 
2. Open account landing page 
3. Open any of the subcategories such as Addresses or Payment 

Issue: There are non navigational elemens whatsoever. The only way for the user to go back to the account landing page is using the browser's back button. Since the account doesn't come with a side navigation where the user can click on the subpages, I recommend to at least add a simple back button element or breadcrumbs to facilitate navigation and user-friendliness. 

![2023-08-07_11h03_36](https://github.com/Xceptance/posters-demo-store/assets/141221329/841dab81-b945-441a-b796-df86d47c18ca)

**Comment by freddyka** [comment]
Issue still remains for poster version 2.1.
