### ISSUE TITLE
Account: button labels on landing page not centered 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#139]
Reproduce: 
1. Log in 
2. Open account landing page 

Issue: The button labels are not horizontally centered, the label displays closer to the upper button border (compare with padding between label and lower button border). I see why it would look funny if the labels got vertically centered within the button but they should at least be centered horizontally. 

![2023-08-07_11h31_04](https://github.com/Xceptance/posters-demo-store/assets/141221329/29da883f-5cea-467e-a64e-e242d0bc352b)

**Comment by freddyka** [comment]
Issue resolved in poster version 2.1.
