### ISSUE TITLE
Order history: order details header incomplete for all but last order

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#140]
Reproduce: 
1. Log into account with at least two saved orders in their history 
2. Go to order history page 

Issue: The header of the individual orders is missing the column labels for all orders except the latest one. Expected to see the column labels "PURCHASED POSTERS", "ORDER DETAILS", and QUANTITY for all orders in the list. 

![2023-08-07_12h58_49](https://github.com/Xceptance/posters-demo-store/assets/141221329/f3ca0e65-656a-4622-a52d-4ef7e52d9e47)

**Comment by EliasTatX** [comment]
This is fixed in v2.2
