### ISSUE TITLE
Order details: should not include product description overview 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#141]
Reproduce: 
1. Log into account with at least one saved order 
2. Open order history 

Issue: The line item display does not only include the product name but also the product description overview. The latter makes sense on a PDP that wants to urge the customer to buy the item. On the order details page it looks a little out of place. I recommend to remove it. 

![image](https://github.com/Xceptance/posters-demo-store/assets/141221329/ede95f8c-1499-4417-942a-56cc0f38c0ec)

**Comment by freddyka** [comment]
Viewing order history after buying a product, return's error page (poster version 2.1).
![Screenshot from 2023-12-15 17-26-57](https://github.com/Xceptance/posters-demo-store/assets/149577992/e4b83f7d-f848-4810-ab2d-edfc46a1a9dc)

Try to :
1.create account 
2.go into account information
3.go to order history--> it should be displayed 
4.purchase a poster
5.go to order history again -->error

**Comment by freddyka** [comment]
Issue is resolved for Poster v2.1.1.
