### ISSUE TITLE
Checkout progress indicator: wording adjustments 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#143]
Reproduce: 
1. Add random item to cart 
2. Start checkout 

Issue: Step 5 and step 6 are named "Checkout" and "Order Complete". While the term "Checkout" feels too unspecific (the whole process is the checkout), "Order Complete" is a phrase, not a single term. I suggest the following: 

1. Change "Checkout" to "Order Overview" 
2. Change "Order Complete" to "Order Confirmation" 

Also see https://github.com/Xceptance/posters-demo-store/issues/134 for a possible removal of step 1 ("Shopping Cart"). 

![2023-08-08_09h27_19](https://github.com/Xceptance/posters-demo-store/assets/141221329/eaa8f9a3-2775-49bd-a64f-05b0e84dc2b2)

**Comment by rschwietzke** [comment]
Wording suggestion coming from #189, cart step can be removed, because we want to remove the indicator iin the cart.

**Comment by freddyka** [comment]
Issue is complete for poster v2.1.

"Checkout" and "Order Complete" changed into "summary" and "completed".
