### ISSUE TITLE
Checkout: account icon should either be hidden or show completely 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#144]
Reproduce: 
1. Add random item to cart 
2. Start checkout 

Issue: The account icon displays in the header and it is incomplete, the user only sees the arrow icon, not the actual figure next to it. Applies to step 2 (Shipping Address) through step 5 (Checkout). 
It is common to hide the account icon in checkout so customers don't get distracted from purchasing. If the link is still supposed to show here, it should show completely. 

![2023-08-08_09h28_50](https://github.com/Xceptance/posters-demo-store/assets/141221329/b3c229ad-a91e-4542-b2b5-6c261d339adf)

**Comment by rschwietzke** [comment]
We want to have the login still being there... so the user knows where to go when they remember that they got an account... even with a gating page as suggested.

**Comment by freddyka** [comment]
Is fixed for posters v2.1.
