### ISSUE TITLE
Shipping/billing forms: mark country field as dropdown 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#146]
Reproduce: 
1. Add item to cart 
2. Start checkout as guest and arrive at shipping step 
3. Click into country field 

Issue: Note the country field is actually a dropdown but there is no arrow icon marking it as such. This also applies to the add/edit shipping and billing address modals in account: 

![2023-08-08_09h53_36](https://github.com/Xceptance/posters-demo-store/assets/141221329/1fc78785-c30f-4bf6-a7c1-aa6ae7851c01)

The icon is actually there for the add shipping/add billing address modals in authenticated checkout: 
 
![2023-08-08_09h53_13](https://github.com/Xceptance/posters-demo-store/assets/141221329/663bde91-9e6d-4256-bafe-affbbd5b3c6d)

I recommend to add the arrow icon to the country field in checkout without saved addresses and in account as well.

**Comment by freddyka** [comment]
Issue fixed for poster v2.1.
