### ISSUE TITLE
Credit card form: expiration date not styled as dropdown 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#147]
Reproduce: 
1. Add item to cart 
2. Start checkout as guest 
3. Arrive at payment method step 

Issue: Note the credit card expiration fields are not styled as dropdowns. This also applies to the add/edit credit card forms in account: 

![2023-08-08_09h58_44](https://github.com/Xceptance/posters-demo-store/assets/141221329/1b816da7-df95-408a-8b02-0345b20ca71d)

![2023-08-08_09h59_24](https://github.com/Xceptance/posters-demo-store/assets/141221329/c3dd9a82-54ee-45dc-8916-23b915e4f406)

The icon actually shows on the add a new credit card modal in authenticated checkout. 

![2023-08-08_09h58_03](https://github.com/Xceptance/posters-demo-store/assets/141221329/61690f13-5987-4629-93b7-a1047c0d4890)

**Comment by freddyka** [comment]
Issue is fixed for poster v2.1.
