### ISSUE TITLE
Order overview: quantity column not read-only 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#149]
Reproduce: 
1. Add random item to cart 
2. Start checkout 
3. Provide valid data at all steps until you arrive at step 5 (Checkout) 
4. Click into quantity field in item list display 

Issue: The field's content can be changed to nonsense. This doesn't affect the order total but the quantity column should be read-only here. 

![2023-08-08_10h43_26](https://github.com/Xceptance/posters-demo-store/assets/141221329/c391b1fa-8436-4e5a-a93e-b6694dceaac8)

**Comment by freddyka** [comment]
is working with posters 2.1
