### ISSUE TITLE
Order confirmation: spelling mistake

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#150]
Reproduce: 
1. Add random item to cart 
2. Start checkout 
3. Provide valid data at all steps 
4. Submit order to arrive on order confirmation page 

Issue: The message to the customer reads "Thank you for purchasing, Your order is complete". The sentence contains a spelling mistake ("Your" shouldn't be capitalized) and is missing punctuation. I recommend the following wording which I find more user-friendly: "Thank you for your purchase, your order is being processed." 

![2023-08-08_10h50_32](https://github.com/Xceptance/posters-demo-store/assets/141221329/31a0b189-9b04-4e6d-8de6-8081f78426a7)

**Comment by EliasTatX** [comment]
resolved during work on #189

**Comment by freddyka** [comment]
Works in poster version 2.1.
