### ISSUE TITLE
Forms: input has placeholder value color 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#152]
Reproduce: 
1. Add random item to cart 
2. Start checkout to arrive at shipping step 
3. Provide data 

Issue: Note the color of the user's input has the same value as the color of the placeholder texts. This shouldn't be the case, actual input should display in a much more prominent manner. I recommend to use black here. 

Global issue, applies to all input fields accross the site. 

![2023-08-08_11h09_25](https://github.com/Xceptance/posters-demo-store/assets/141221329/f9661dce-ee50-45d7-92bf-52433460de98)

**Comment by freddyka** [comment]
Text color is now more prominent in poster version 2.1.
