### ISSUE TITLE
Footer updates

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/posters-demo-store#159]
Update the footer of the storefront and put this information in:

*ABOUT POSTER*
The Poster Store is a small e-commerce demo application. It is meant for functional testing, test automation, and load and performance testing. It can also help you to learn programming better. This software is licensed under Apache License 2.0. 

Github logo and link

*INFORMATION*
This software is for demo and testing purposes only. Orders will not be fulfilled. Do not enter sensitive or personal data! 

*CONTACT INFORMATION*
Xceptance GmbH
Leutragraben 2-4
07743 Jena
Germany

Phone	+49-3641-376300
Email	kontakt@xceptance.de
WWW     www.xceptance.com

*Copyright subheadline*
Copyright (c) 2013-2023 Xceptance Software Technologies GmbH

**Comment by freddyka** [comment]
Footer is updated in the new posters version 2.1.

Note: there are few differences :

-WWW (http://www.xceptance.com/) is now displayed as Website: (https://www.xceptance.com/)

-a new heading :
Customer Care
    [Contact]


@rschwietzke do these changes matter?
