### ISSUE TITLE
Forms: "Required fields" note looks out of place 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#165]
A global issue regarding the address forms across the site: Most of them display an explanation for the asterisk, i.e. "* Required fields". This note looks a little out of place in many of the foms. 

See for instance the shipping form at step 1 of checkout, where it displays left-aligned right above the red CTA:

![image](https://github.com/Xceptance/posters-demo-store/assets/141221329/f9d696ad-974c-4e40-9a22-21acb88659e1)

The registration form, on the other hand, displays the note on the same line as the CTA which looks even more awkward: 

![2023-08-09_10h27_37](https://github.com/Xceptance/posters-demo-store/assets/141221329/f18c9d14-a40e-45fb-8af8-1bab57d88aef)

The note is missing on the add address modals in checkout. 

For the sake of consistency, I recommend the following: Do not display the note and add "(Optional)" to the placeholder values in the form fields that are not required. The meaning of the asterisk with regards to forms is widely known, most of the stores don't explicitly display an explanation anymore.

**Comment by kqmpetenz** [comment]
We also need to be consistent with the button placement. I suggest we put the button below, not besides the "Required fields" String.

**Comment by rschwietzke** [comment]
PO: Let's come up with a consistent dialog layout first and we can apply that to all similar dialogs and solve all issue at once.

**Comment by freddyka** [comment]
Issue resolved for poster version 2.1.

Note: required fields isn't out of place anymore
