### ISSUE TITLE
Shipping/billing forms: name should be two individual input fields 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#166]
Reproduce: 
1. Add random item to cart 
2. Start guest checkout 
3. Arrive at shipping form 

Issue: Note the from consist of only one input field for the name value. This is not standard behavior, the name usually consists of at least two separate input fields, i.e. first name and last name. This is actually the case for the personal data section in the user's account and the registration form but it has not been done for the shipping and billing form. Thus, this applies to: 

- shipping form in checkout incl. add shipping address modal in authenticated checout 
- billing form in checkout incl. add billing address modal in authenticated checkout 
- add/edit billing and shipping address in the user's address book in account 

Wrong: 
![2023-08-09_10h38_48](https://github.com/Xceptance/posters-demo-store/assets/141221329/f80c2094-5667-4ab2-992f-a378b095920b)

Correct: 
![2023-08-09_10h45_13](https://github.com/Xceptance/posters-demo-store/assets/141221329/15126ecf-cee7-4c65-bd38-3da01855f941)

**Comment by freddyka** [comment]
Issue remains for poster version 2.1.

Note: also applies when adding another shipping or billing address as logged-in user in the checkout procedure 
![Screenshot from 2023-12-14 10-00-32](https://github.com/Xceptance/posters-demo-store/assets/149577992/2ca22cf1-e8d3-4538-817d-8cf00b958557)

**Comment by msaroshali** [comment]
Requires a concrete solution. To be continued with #318
