### ISSUE TITLE
Account, saved credit card: avoid wrapping 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#170]
Precondition: You're a registered user with svaed credit card(s). 

Reproduce: 
1. Log in 
2. Go to Account > Payment Settings 

Issue: The labels "Credit Card" and "Valid to" wrap onto two lines without any need. Please adjust this to display on one line. 

![2023-08-09_13h03_38](https://github.com/Xceptance/posters-demo-store/assets/141221329/3df12dfc-eb0f-4591-b0fd-22d794b236da)

**Comment by freddyka** [comment]
Issue is fixed for Poster version 2.1. 

But: There is an extra line, when Firefox browser window is in "side-by-side" view.

@rschwietzke can this issue still be closed? 
![Screenshot from 2023-12-14 09-29-38](https://github.com/Xceptance/posters-demo-store/assets/149577992/58721be9-6993-40e4-86e3-11785de4e712)

**Comment by rschwietzke** [comment]
@freddyka 
Please open a ticket with the requirement to style that page/dialog appropriately and close this one after that.
