### ISSUE TITLE
Delete account: not working with item(s) in cart

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#172]
Reproduce: 
1. Log in 
2. Add item to cart 
3. Go to Account > Personal Data 
4. Click "Delete your account" 
5. Provide valid password 
6. Submit 

Issue: See an error page. 

![2023-08-09_13h10_19](https://github.com/Xceptance/posters-demo-store/assets/141221329/de8c2236-c3dc-45e5-bd4c-1dcae224b85b)

Account doesn't get deleted if the user has items in their cart, I can log in again afterwards.

**Comment by KFie** [comment]
@msaroshali I rechecked and modified the steps to reproduce - the issue occurs as soon as the user has an item in the cart.

**Comment by freddyka** [comment]
Issue still remains for poster version 2.1.

New error window displayed:
![Screenshot from 2023-12-14 09-09-40](https://github.com/Xceptance/posters-demo-store/assets/149577992/0c242232-cada-47d7-9325-c7263535acfb)

**Comment by msaroshali** [comment]
@freddyka Could you please test this again, against the **L&G** posters and make sure you are on develop branch, as I do not have the same error occurring anymore.

**Comment by freddyka** [comment]
@msaroshali error remains with updated posters version

**Comment by freddyka** [comment]
Error is resolved.
