### ISSUE TITLE
Account, change password: field label wraps onto two lines 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#174]
Reproduce: 
1. Log in 
2. Go to Account > Personal Data > Change your password 

Issue: The field label "Repeat new password" wraps onto two lines which isn't necessary here. Please display this on one line. 

![2023-08-09_13h21_54](https://github.com/Xceptance/posters-demo-store/assets/141221329/9509c7e2-ffc3-4d21-a534-8428ec01bda5)

**Comment by freddyka** [comment]
Fixed in poster version 2.1.
