### ISSUE TITLE
Account, change name or email: change order of last and first name field 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#175]
Reproduce: 
1. Log in 
2. Go to Account > Personal data > Change name or email 

Issue: The order of the name field is not common in DE and US with last name displaying first. Please change the order to "First name", followed by "Last name". 

![2023-08-09_13h27_19](https://github.com/Xceptance/posters-demo-store/assets/141221329/f25a3998-9073-445a-9b73-fd63efb97d94)

**Comment by freddyka** [comment]
Issue still present for posters version 2.1.
