### ISSUE TITLE
Account, change name or email/delete address or account: revise field labels 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#176]
Reproduce: 
1. Log in 
2. Go to Account > Personal Data > Change name or email 

Issue: All field labels include the pronoun "Your". 

![2023-08-09_13h34_28](https://github.com/Xceptance/posters-demo-store/assets/141221329/7c56589e-caf8-45cd-aa0d-beb830869b6a)

Also applies to all delete options in the account section, i.e delete address, delete credit card or delete account: 

![2023-08-09_13h35_10](https://github.com/Xceptance/posters-demo-store/assets/141221329/3639c632-2682-4343-8d1d-ea24acc618be)

This is inconsistent with other places across the site, compare with change password form, add/edit address forms, etc. I recommend to remove the pronoun so that the labels only read: Last name, first name, email, password. 

Change password form: 
![2023-08-09_13h37_58](https://github.com/Xceptance/posters-demo-store/assets/141221329/663c5aa1-d11c-438c-ba10-017e2c8d7a28)

Edit shipping form: 
![image](https://github.com/Xceptance/posters-demo-store/assets/141221329/dede5103-e6a4-4e01-b8fd-4d82f6556450)

**Comment by freddyka** [comment]
Issue still present for posters version 2.1.
