### ISSUE TITLE
Account flyout: change greeting message 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#179]
We should improve the greeting message on the account flyout. Current display: 

Guest users: "Welcome: Guest" 
Authenticated users: "Welcome: [First name]" 

Possible improvement: 
Gest users: "Welcome!"/ "Hi!"/ "Hello!"
Authenticated users: "Welcome/hi/hello, [First name]!" 

![2023-08-10_09h51_18](https://github.com/Xceptance/posters-demo-store/assets/141221329/e2eb5189-e504-43d9-9954-db1701614e95)

![2023-08-10_09h51_35](https://github.com/Xceptance/posters-demo-store/assets/141221329/0013229c-2f03-4304-9523-1ef49cc297ad)

**Comment by freddyka** [comment]
Issue still present for poster version 2.1.

Current display: Welcome:Guest / Welcome: [first name]

**Comment by EliasTatX** [comment]
I would like to request another review of this ticket. The change I made back in November changed this to Welcome: [first name] for logged in users and just Welcome for guests. This should have been the case when it was reviewed and it is currently the case on the live site after the changes were pushed. If this is not acceptable please clarify accordingly, however I can not replicate the guest message displaying "Welcome:Guest" on both the live version and the versions under development as the review indicates.
