### ISSUE TITLE
Guest checkout: data not retained when returning to previous steps

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#180]
Reproduce: 
1. Add random item to cart 
2. Start guest checkout 
3. Provide valid shipping and billing data and proceed 
4. Provide valid credit card data and arrive at step 5 (Checkout) 
5. Use breadcrumbs (or browser back) to return to any of the previous steps 

Issue: The forms are empty which makes it impossible to edit existing input. If the user wants to change something, they have to start all over again. The previous input should be retained here. 

https://github.com/Xceptance/posters-demo-store/assets/141221329/38f5d728-dc65-452a-bc3e-062408779f3a

**Comment by freddyka** [comment]
Issue not fixed for poster version 2.1. 

No more breadcrumbs to use to navigate between checkout steps.
When using "browser back" the forms are empty and no input is saved.
