### ISSUE TITLE
ProductDetailPage: validation of some elements only possible via style classes 

### ISSUE THREAD

**Issue by kqmpetenz** [Xceptance/posters-demo-store#187]
Issue: The section headline strings "Product Description:", "Select size:" and "Select style:" are only accessable via style selector. Only the section headline string "Print Information:" is accessable via specific id.

![2](https://github.com/Xceptance/posters-demo-store/assets/65414932/54cc77e8-0f31-4f3c-a57c-9621117fd2c4)
![1](https://github.com/Xceptance/posters-demo-store/assets/65414932/e79ff724-6995-4a63-b7a8-4d2aae4d9dd9)

**Comment by freddyka** [comment]
Product description and print information headline were deleted in poster v2.1, select style and select size are now accessible with classes.
