### ISSUE TITLE
Update Checkout Progress Indicator

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/posters-demo-store#189]
New design and labeling. 

![image](https://github.com/Xceptance/posters-demo-store/assets/1793856/3ed52029-246c-40fe-8122-d4a2ddad313d)

* Font size text: 0.875rem
* Font size numbers: 1.5rem
* black: # 111
* circle size: 60px
* distance text and circle: 10px

**Comment by KFie** [comment]
Also see https://github.com/Xceptance/posters-demo-store/issues/143.

**Comment by freddyka** [comment]
The issue hasn't been completely resolved for poster v2.1.

There has been a style changes for the issue that looks almost the same but has different attributes.
Differences:
1.font size is 12px, this doesn't match the adjustment of the 0.875 rem
2.font size of the numbers inside the circles also differs from the required ones
3.distance of the text and circle is not the required 10px
