### ISSUE TITLE
go to PlaceOrderPage: some elements differ from CartPage even though they are the same

### ISSUE THREAD

**Issue by kqmpetenz** [Xceptance/posters-demo-store#191]
Issue:
1. product price representation PlaceOrderPage (e.g. `$ 0.00`) differs from product  price representation CartPage (e.g. `$0.00`)
2. price summary tax headline PlaceOrderPage (`Tax (6.0%)`) differs from price summary tax headline CartPage (`Tax (6%):`)
3. price summary total headline PlaceOrderPage `(Order Total)` differs from price summary total headline CartPage `(Total)`
4. table head PlaceOrderPage (`Products`) differs from table head CartPage (`Product`)

PlaceOrderPage:
![7](https://github.com/Xceptance/posters-demo-store/assets/65414932/e2d665a6-805f-4900-aa50-81296019c96a)

CartPage:
![8](https://github.com/Xceptance/posters-demo-store/assets/65414932/db6f5496-8039-4b0f-8b55-62c46b76a4d8)

**Comment by KFie** [comment]
Issue #1 applies to unit price value as well.

**Comment by freddyka** [comment]
Issue fixed for poster v2.1.
