### ISSUE TITLE
Fonts, Font Sizes, Buttons

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/posters-demo-store#192]
Establish a consistent font handling across the store. We will go with two fonts currently and might change that later if needed, plus an icon font.

* 16px is the base font size, hence this will be 1rem
* The default font is [Rokkitt](https://fonts.google.com/specimen/Rokkitt), weight 400, regular, serif
* The second font for longer text will be [Montserrat](https://fonts.google.com/specimen/Montserrat), weight 400, regular, sans-serif
* The icon font is [icomoon](https://icomoon.io/#app-features), as the free version: https://icomoon.io/#preview-free

# Elements
* Category Menu: 1.1 rem, uppercase, Rokkitt, 400, #111
* Promo Header: 1.1 rem, uppercase, Rokkitt, 400, White
* Input boxes: 1rem, Montserrat, 400, #333
* Product tiles: 1rem, Rokkitt, 400, #111
* Footer: Headlines, 1 rem, uppercase, Rokkitt, 400, #111
* Footer: Text, 0.875 rem, Montserrat, 400, #111
* Buttons: border-radius: 10px, 1rem, uppercase, Rokkitt, 400, white on #cb1b1b, hover color #a30000, border color equals background-color
* Call to action button: White text on red
* Normal button: black text on white, button just outlined

All fonts and fonts variants have to be locally installed, aka not font loading from Google or other third-parties. Enhance the README with information about the source and license of the fonts.

# Dialogs
* Box: bg-color #f9f9f9, border-radius: 10px
* Headline: left, Rokkitt, 400, 1.5rem, #111111, uppercase
* Help text underneath: Montserrat, 1rem, #555555
* Label text: Rokkitt, uppercase, #555555, 0.875rem
* Input: 1rem, Montserrat, 400, #111111, 1rem
* Buttons: border-radius: 5px, 1rem, uppercase, Rokkitt, 400, white on #cb1b1b, hover color #a30000, border color equals background-color

![image](https://github.com/Xceptance/posters-demo-store/assets/1793856/37321495-1492-4532-8618-6932b6662819)

**Comment by KFie** [comment]
@rschwietzke Does this include the radio buttons? Maybe we should consider a specific styling (red, conforming to brand) here as well... 

![2023-08-14_09h54_56](https://github.com/Xceptance/posters-demo-store/assets/141221329/53f34a04-7379-404e-a711-b1c71911528f)

![2023-08-14_09h55_10](https://github.com/Xceptance/posters-demo-store/assets/141221329/4960cf54-67be-42b6-bb59-654380f369ce)

**Comment by EliasTatX** [comment]
What is the deciding difference between buttons, call to action button and normal button in this case and how should the styling of call to action buttons differ from buttons, since those are already red with white text?

**Comment by EliasTatX** [comment]
Any styling requirements for the various headlines across the pages? Especially the names of products displayed under their image seem like adjustments should be made to the current version

**Comment by rschwietzke** [comment]
The main button is the call-to-action button, the one the customer should preferably use. It also should be at the same position all the time, mostly on the right side. All other buttons that we offer but not heavily invite the user to press it, are white. Often that is also called primary and secondary button:

**Comment by rschwietzke** [comment]
Headers need also consistent styling but one thing at a time. Finish this now, make the branch usable, so the PO can view and agree. Rest comes next.

**Comment by EliasTatX** [comment]
First round of work on this ticket is ready for review.

**Comment by rschwietzke** [comment]
Let's close that for now and file defects for all other odditities
