### ISSUE TITLE
Cart/checkout: order details header should have consistent font weight 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#193]
Reproduce: 
1. Add item to cart 
2. Open cart page 

Issue: the "Item Total" value in the order details header is bolded while the other elements in the header are not. This should be consistent. If we want to stick with the font in all caps here, we should probably not show all values in bold to not make them more prominent than the actually line item details. Also see https://github.com/Xceptance/posters-demo-store/issues/142 in this context. 

Applies to: 
- Cart
- Checkout step 5 (order overview) 

![2023-08-11_09h32_26](https://github.com/Xceptance/posters-demo-store/assets/141221329/d5e156cc-68ca-4766-bef1-2c9ca315ed04)

![2023-08-11_09h33_44](https://github.com/Xceptance/posters-demo-store/assets/141221329/c8470b9e-13d8-46bd-bfa6-6e7a05f6500f)

**Comment by rschwietzke** [comment]
See also #192 This all be in the realignment of fonts. Ask the PO if it is not clear how the cart should look like based on the standard fonts.

**Comment by freddyka** [comment]
Issue is fixed for poster v2.1.
