### ISSUE TITLE
Cart: updating quantity sets tax to 0

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#194]
Reproduce: 
1. Log in 
2. Add random item to cart 
3. Open cart 
4. Change quantity and click to update 

Issue: the tax value is set to 0, thus also changing the order total. Only on reload do I see the correct tax and order total.

Only happens for authenticated users, cannot reproduce for guest users.

https://github.com/Xceptance/posters-demo-store/assets/141221329/4740d827-5ba0-47d0-9d37-1bfe857ff884

**Comment by freddyka** [comment]
The issue is resolved for poster v2.1.
