### ISSUE TITLE
Account: address or credit card deletion should not require password submission 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#198]
Reproduce: 
1. Log into account with at least one saved address 
2. Go to Account > Addreses
3. Click to delete address 

Issue: user arrives on a form asking for their password. Applies to credit card deletion as well. 

Is this really necessary? Usually, users are only asked for their password when wanting to change their email or password. Deleting addresses or payment methods should be easier. 

Suggestion: When users delete their address or credit card, this should either happen instantly. Alternatively, the system could display a "Remove confirmation modal" asking the customer if they really want to delete this address/credit card. 

![2023-08-11_11h10_53](https://github.com/Xceptance/posters-demo-store/assets/141221329/01e57d41-9bed-419c-8e24-5f21ffe0c255)

![2023-08-11_11h11_12](https://github.com/Xceptance/posters-demo-store/assets/141221329/84f99362-c264-4a2b-bd1b-764e63b1b5a8)

**Comment by rschwietzke** [comment]
Requires a confirmation  modal, not a password request.
