### ISSUE TITLE
Mobile PLP: padding inconsistency 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#215]
Environment: mobile 

Reproduce: 
1. Open random category landing page such as https://34.70.184.112:8443/posters/topCategory/Panoramas?categoryId=4

Issue: there is an inconsistency in the padding between the product images. On desktop, the row wraps onto the next line after the third item. On mobile, the padding after the third (and 6th, and 9th...) image is larger than the padding between the other images which is noticeable. 

Regular space between images: 232px
![2023-08-16_11h13_48](https://github.com/Xceptance/posters-demo-store/assets/141221329/42887010-ffdf-431f-ba50-17633f0946ff)

Space between 3rd and 4th image: 288px 

![2023-08-16_11h15_01](https://github.com/Xceptance/posters-demo-store/assets/141221329/90b3f665-2c24-4838-99ae-9a6e90295ab2)

**Comment by freddyka** [comment]
Issue fixed with new poster v2.1 design.
