### ISSUE TITLE
Mobile PLP: images not centered 

### ISSUE THREAD

**Issue by KFie** [Xceptance/posters-demo-store#216]
Environment: mobile (here: iPhone 1 mini, iOS 16.3.1, Nokia 7.1, Android 10) 

Reproduce: 
1. Open random category landing page such as https://34.70.184.112:8443/posters/topCategory/Panoramas?categoryId=4

Issue: the product images are not centered on the page. Looks like they display a little closer to the left than the right, This way, the product name, description overview and price are also not centered below the image. 

Similar to https://github.com/Xceptance/posters-demo-store/issues/201. 

![2023-08-16_11h31_18](https://github.com/Xceptance/posters-demo-store/assets/141221329/1738d597-ba73-4571-b5a7-4cac06e6dff8)

**Comment by freddyka** [comment]
Issue fixed for poster v2.1.
