### ISSUE TITLE
Fix layout problem backoffice

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/posters-demo-store#223]
The current backoffice shows an odd white void between navigation and main content. The original theme does not: 

## Original
![image](https://github.com/Xceptance/posters-demo-store/assets/1793856/79dab32e-e4ca-47c9-947a-dea7890215e1)

## Current Backoffice
![image](https://github.com/Xceptance/posters-demo-store/assets/1793856/23569e71-6e70-4191-9036-d09d47bbf444)

**Comment by msaroshali** [comment]
Depends on the size of the screen. The original theme also shows the same void, at full screen. Couldn't discern any visible differences between the template and our back office, except the footer.
