### ISSUE TITLE
Carousel-indicators and buttons not working properly

### ISSUE THREAD

**Issue by freddyka** [Xceptance/posters-demo-store#287]
Poster v2.1
1 go to posters front page
2 navigate with in the carousel with the indicator buttons
3 try also using the arrow buttons 
--> issue : can't click on the 4. Indicator button to see the last picture, when using the arrow buttons you're stuck on the last panorama picture and cat navigate anymore
![Screenshot from 2024-01-04 10-53-27](https://github.com/Xceptance/posters-demo-store/assets/149577992/20bb6d3b-4c3d-4030-acb6-df4df8da8e5e)

**Comment by msaroshali** [comment]
Should be working with the patch or v2.1.1. Please verify again.

**Comment by freddyka** [comment]
Issue is resolved for poster v 2.1.1
