### ISSUE TITLE
Close window button not working

### ISSUE THREAD

**Issue by freddyka** [Xceptance/posters-demo-store#291]
For poster version 2.1
1 log into account that has billing/shipping address saved
2 go to checkout
3 click add new billing/shipping address 

![Screenshot from 2024-01-04 11-34-10](https://github.com/Xceptance/posters-demo-store/assets/149577992/908290a9-1d8f-4e63-a320-1edaeaa70735)

-->issue closing the window with the x button isn't working (only way to close is browser back or clicking next to the input window)

**Comment by EliasTatX** [comment]
this issue is not present anymore as of v2.2
