### ISSUE TITLE
Add new credit card link in checkout not working

### ISSUE THREAD

**Issue by freddyka** [Xceptance/posters-demo-store#292]
For poster v2.1
1 log in account with saved credit card info 
2 go to checkout 
3 go to payment

-->issue: cant use the add new credit card link in checkout
![Screenshot from 2024-01-04 11-49-33](https://github.com/Xceptance/posters-demo-store/assets/149577992/182c052b-2ef9-4f74-bace-eec96caebb0d)

**Comment by EliasTatX** [comment]
not present anymore as of posters v2.2
