### ISSUE TITLE
Uniformize the class and #ID names throughout the Poster Demo Store excluding the Back office

### ISSUE THREAD

**Issue by msaroshali** [Xceptance/posters-demo-store#299]
**Class Names**
- We use `kebab-case` for class names.
- Keep class names as short and simple as possible for example `checkout-progress-indicator-cart-page` should be a big :x:
- Specifically for class names, being used by JS, should start with _js_  for example `js-add-to-cart` instead of just `add-to-cart`

**#ID Names**
- one word lowercase IDs are recommended, but should be self-explaining. Can use camelCase for IDs, but the usage should be kept to a minimal. Use **Only** if it is unavoidable. We do not want to use `kebab-case` for IDs as it would make them indistinguishable from class names.

**Comment by rschwietzke** [comment]
Classnames only used by JS should start with `js-`. If you use that for styling and JS, don't do the `js-` part. IDs can be one word or also kebab but should be simple and dedicated aka cart, order-form, order-summary, and so on.
