### ISSUE TITLE
Modify Address Tables in DB to have two columns for the name instead of a single column.

### ISSUE THREAD

**Issue by msaroshali** [Xceptance/posters-demo-store#318]
In continuation of #166 

- Shipping and Billing address forms now have been modified to incorporate a First name and a Last Name separately.
- This is being handled currently server side inside the controller, but is being stored inside the DB as a single name. 
- Modifications are required to the existing relevant tables inside the DB to have two separate columns (First Name, Last Name) instead of just a single column for holding the full name.

**Comment by msaroshali** [comment]
@rschwietzke Do we need to implement these modifications for credit card info as well in addition to shipping and billing address?

**Comment by rschwietzke** [comment]
@msaroshali CC have only a name field and don't know first and last name.
